### ISSUE TITLE
[feat]: Implement a pricing controller

### ISSUE THREAD

**Issue by jsanmigimeno** [catalystdao/generalised-relayer#31]
Implement a pricing controller to allow external services (e.g. an underwriter) to query an asset price via the Relayer without it itself having to implement a pricing service.

**Comment by ptdatta** [comment]
Hey @jsanmigimeno can you please review [this PR.](https://github.com/catalystdao/generalised-relayer/pull/41)

**Comment by jsanmigimeno** [comment]
Implemented via #42
